language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: WiLuyCiERlx5Sr72J+bWzYWgnmpZpereVJfhKQ2KOb7OpigoEbKstQyAhHXE/lY3EhOp9wTxZ8z7EwkThYlg2U4krZV8+rqWIuykNOarP7+v4gLpbtEVZnoFNDX/V93OVjHZXNBaGlLm5AmS/165z3M2SKgrPfd7myL7nH85sfe7qMLi8uBFUw2e3+PC87SDaxQeFL5cvcJZQihC4kTQ2XfUOJxOxvHebqQHPuG33r3noJZ30KwPfzW4TEYqrKIE830IT2THnTq+txbglBNxJA+fk+kVDAwkmzw5zwsO8E9so/SabmxgHEQay9CJXPSLUvSu256hyKSFM2OYqjPw8/c0dT+d5RKavqpTbzLjtL73ck5tS7hIjnt0y5nQ+8czrgZfRTslDNhBxEaCQm6t5jzm9qLRZzSvwmurTXVw6tZaPDG4oaET0RrDG7RQrY3VcnS+x2wJPuRWLKpSvcqaVMaduAtCN4tROztOv6wcrcO2JcDKXP/LFlgPKipAqJ167KZEkUcyiC5m8FMQfeYK2yJHY/+HLWhm6c4Wjr2yZaKmiSvNRYvtujM5yfmXZmvs/8osTRLpo8FbeRrFTUQbEQ+eX4yHSPA1dSCsiBxhRDeWCzXKFSQNMtg1g+WkgawDWCQ5dz8U7wuMAka9WXttNgUUeP+Qy1+YxjQSRRmjfzs=
  on:
    tags: true
    repo: raman325/pyclimacell
    python: 3.8
