language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: lrcWFVsAzguw8IFmpzIrrnDrPe+1wau2wT9mysM07Bl/oeJqG70OKaRkgB5pt8B21oBoFXy6eYoiOo9gY1tDHtToYOT9s853Cf4a9d6P7jJUKIdpjg6lSaLpu5hkifgL1lQxJjexVAH9XTtOIsUu5CN5naf6CzAtD16NblP7DSctccRkKlCXAMXnXw2Von6uhP5pO62wuCW7lbZzK1YSD86azQFRUF+LLAF2FdL7kZqC8akrNmCi6Xt/cbZ5iEyFfpH9HDlHmsBlpufRfSETIQqeUZIWYHIXgpKGA5UWMiTDcI9lSRRhGxzoa4drkrPPXs4hIi0lIEdTUzhs2ClUzvVY8ry4Oqv0S6IieOY0dDA3hDJ40F66lmmUWbpvmCRJIBr6RqO2dkcgeHCOTor2PE+Adn9XI7A/FE1SPSYLv48ylvwaCrLxTn8Ir+1oDGiX/uM2NPxqWzu0uEXLa1yg8iAuj5wcPaviNSF7buSDady8fcbJ0LGatLx1ZZvHhLExI+f3dLlTy5WKEfQjH3KEaZHvapX6doxvU+mONGyf5zJe92JlkQcVXynHGYpmFs9We6VPR1VK8ZX/IAYafSOOZHlHD7sIAxtIAj0j0PziTrs3dVntZA22vlqundC+OdTibHxrHk2obxfoYY9zHjZih9evqzblCHPvfYdz6X5g3Wc=
  on:
    tags: true
    repo: raman325/pyclimacell
    python: 3.8
