language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: gU4Q9QGtGINw8m03ctskm/3kg/GNSVQs0TZY8Aw+G3ry2ey0X2yseXai4RAs9vZdycS4+kn2hCgabwvErH+lNO/WLJiaKUMl+hPzpkTXUrqJLOArqUOf3QhuaFfvtGckEiUr2qiIjmG7QwjwJyHZy0wgIMhrcgGm0o9Xtnyrnph12yk0MB2wQCdKqQKuV+ICCCmXX2IYrDT1y+I7zGYVGQ/zraDjv3/CSiN/aRFEC4AXg06l4P0dU7aMxaJE4gF/fY2QUyAj+V2TBTEqApPnVCDlsd6e1l87WKm6xvBUYcJfAU5rJoJ8EDsZ8a03q+3zPxJii+nPvOsQuVdJlizxkAqo6VBI4MS/dJtynELw9IzXTyA3F9F+BJFqK4P454iWeIfEEzP05a35kZCktRIimnMVB5tqS+30hHLNZplioKkcqrbPClgHen+BM9dvJ34MeLQ/YH0Swt+bGusBnAc8xiYfJ3xP2X7uN0fITVtV5Tyl41trqGjbbGA4ukuzhgIl8iOh812SElJ1/FU0MKH6F4RPgyp8+8qceFN5JN70vZKcelOBl3TOmOSn5R4gJomg35YSxy7KtjSd4Yii0A/fLUCv0Bccs6zGbPWQoirDALpkKu0kLJfaSiw2r2duGRx/5dcKWwu17xeVGao0rpJDRBQdgDvZKRhBiT53JsNmqnY=
  on:
    tags: true
    repo: raman325/pyclimacell
    python: 3.8
